### ISSUE TITLE
code font

### ISSUE THREAD

**Issue by shrekuu** [RaphaelDDL/google-prettify-monokai-theme#2]
Hey @RaphaelDDL ,  I think it might be better if you set a font on the code. Mac has `menlo`; windows and linux has `Consolas`. So you can do `font-family: menlo, Consolas, arial, sans-serif`.
 :)

**Comment by RaphaelDDL** [comment]
Hi @shrekuu, that would be cool.
I was thinking in make some changes to the CSS, making the rounded-box on pre/code as a separated class (so people would have to add  `prettyprint` and `pp-box` for example) and the same with anything else.
So I could do the same for `.pp-font` or something like that with the `font-family` declaration, making it optional.

What you think?

Also, thanks for the suggestion :)

**Comment by shrekuu** [comment]
Hi @RaphaelDDL , thanks for your reply. 
That would be better, so people could use the optional default font or set their own font. :)
Here is another recommended font-family `consolas, menlo, courier, monospace`.
